// Riri Analytics → Excel / PDF.
//
// The officer says yes; the server re-runs the query, builds a real workbook or PDF,
// writes it to private storage under an autogenerated name, and returns a signed link.
//
// ⚠ THE ROWS ARE RE-READ HERE, NEVER ACCEPTED FROM THE BROWSER. If the client posted
// the result rows, anyone could edit a figure in devtools and download an
// official-looking BirgenAI workbook containing it — with our name on the cover.
//
// The SQL does arrive from the client, and that is fine: it goes through exactly the
// guard and read path everything else does (validateReadSql → runReadQuery — SELECT
// only, whitelisted views, read-only transaction, tenant-stamped by RLS, row-capped,
// timed out). It earns no more trust than a string typed into the chat box, which is
// the threat model that layer was built for.
import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { requireRight } from "@/lib/rbac/authz";
import { requireFeature } from "@/lib/billing/entitlements";
import { meter } from "@/lib/billing/meter";
import { prisma } from "@/lib/prisma";
import { validateReadSql } from "@/lib/riri/guard";
import { runReadQuery } from "@/lib/riri/readpath";
import { exportName, toExcel, toPdf, EXPORT_MIME } from "@/lib/riri/export";
import { putReportObject, signedUrl, DOCS_BUCKET } from "@/lib/storage/provider";

export const runtime = "nodejs";

/** Long enough to actually download a big workbook, short enough to be a link not a leak. */
const REPORT_URL_TTL_SEC = 3600;

export async function POST(req: NextRequest) {
  const session = await auth();
  if (!session?.user?.orgId) return NextResponse.json({ success: false, message: "Sign in." }, { status: 401 });
  const orgId = session.user.orgId;

  const denied = await requireRight(session, "riri.use");
  if (denied) return denied;
  const gated = await requireFeature(orgId, "riri");
  if (gated) return gated;

  let body: { question?: string; sql?: string; format?: string };
  try { body = await req.json(); } catch { return NextResponse.json({ success: false, message: "Invalid request." }, { status: 400 }); }

  const question = (body.question ?? "").trim() || "Report";
  const format = body.format === "pdf" ? "pdf" : "xlsx";
  const sql = (body.sql ?? "").trim();
  if (!sql) return NextResponse.json({ success: false, message: "Nothing to export — that answer had no query behind it." }, { status: 400 });

  const guard = validateReadSql(sql);
  if (!guard.ok) return NextResponse.json({ success: false, message: `I won't run that: ${guard.reason}` }, { status: 400 });

  const res = await runReadQuery(orgId, guard.sql);
  if (!res.ok) return NextResponse.json({ success: false, message: `Could not re-run the query: ${res.error}` }, { status: 400 });

  const org = await prisma.org.findUnique({ where: { id: orgId }, select: { name: true } });
  const meta = {
    question,
    lenderName: org?.name ?? "Your lender",
    sql: guard.sql,
    actorName: session.user.name ?? null,
  };

  const filename = exportName(question, format);
  const buffer = format === "pdf" ? await toPdf(res.rows, meta) : await toExcel(res.rows, meta);

  let key: string;
  try {
    key = await putReportObject(orgId, filename, buffer, EXPORT_MIME[format]);
  } catch (e) {
    console.error("[riri:export]", e);
    return NextResponse.json({ success: false, message: "Built the report but could not store it." }, { status: 500 });
  }

  const url = await signedUrl(key, REPORT_URL_TTL_SEC, DOCS_BUCKET);

  await prisma.auditLog.create({
    data: {
      orgId, actorId: session.user.id, actorType: "staff",
      action: "riri.export", entity: "RiriReport", entityId: key,
      meta: { question, format, rows: res.rows.length, filename },
    },
  }).catch(() => {});
  void meter(orgId, "riri_query", 1, { model: "analytics", mode: "live", route: "export" });

  return NextResponse.json({
    success: true,
    filename,
    rows: res.rows.length,
    // Simulation storage returns a `sim/` key and no signed URL — say so rather than
    // handing back a dead link.
    url,
    stored: !key.startsWith("sim/"),
  });
}
