// GENERATED BY scripts/media.mjs - DO NOT EDIT BY HAND.
//
// One entry per shipped image: a ~20px blurred WebP as a data URI, the picture's
// own dominant colour, and its real dimensions.
//
// WHY THIS IS INLINE RATHER THAN FETCHED. The placeholder's whole job is to be
// on screen during the first frame, before the photograph it stands in for has
// even been requested. A placeholder that is itself a request cannot do that job
// - it arrives in the same round trip as the thing it was covering for.
//
// Re-run `npm run media` after dropping a wallpaper into public/themes.
export type MediaMeta = {
  /** A ~20px WebP, base64. Painted blurred and scaled up under the real one. */
  lqip: string;
  /** The picture's own dominant colour - the ground behind it while it loads. */
  dominant: string;
  w: number;
  h: number;
};

export const MEDIA: Record<string, MediaMeta> = {
  "/images/suite/login-analytics.webp": { lqip: "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAAAQAwCdASoUAA0APu1iqk2ppaQiMAgBMB2JQAARO0o5lS4A/vDu+kZiRZo8+s7BnYG3m+nXrCkkQXuFAAA=", dominant: "#080808", w: 1586, h: 992 },
  "/images/suite/login-books.webp": { lqip: "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAgCdASoUAAwAPu1kqU4ppaOiMAgBMB2JZwAAe/QAAP7w//vDKo7NnzzgiAIAAAA=", dominant: "#080808", w: 1536, h: 944 },
  "/images/suite/login-desk.webp": { lqip: "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAAAQAwCdASoUAAwAPu1yrU+tJ6QiMAgBoB2JYwAAW+snkcgA/vQasc51/slzxw70JSOHGJJrgAA=", dominant: "#080808", w: 1536, h: 944 },
  "/images/suite/login-lending.webp": { lqip: "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAwCdASoUAA0APu1kqk4ppaQiMAgBMB2JYwAAibIIi7QA/vB18I09Wt2wLUavHrkzT7udQg/sT++YV0gT0fnn1o4AAA==", dominant: "#080808", w: 1586, h: 992 },
  "/images/suite/login-people.webp": { lqip: "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADwAgCdASoUAAsAPu1iqU2ppaQiMAgBMB2JZwDE2C0kAAD+8Ixsd/oprMJ//vqbZwmWpE9gAAA=", dominant: "#080808", w: 1344, h: 768 },
  "/images/suite/login-portal.webp": { lqip: "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACQAwCdASoUAAwAPu1iqU2ppaOiMAgBMB2JYwABHutzG9EyYBgAAP7+bebpjSsFeX/nu9uT8G6MH1Dx5/Jn59feKk3ClZUffAAAAA==", dominant: "#080808", w: 1536, h: 944 },
  "/themes/boda-motion.webp": { lqip: "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAwCdASoUAAwAPu1orU6ppiSiMAgBMB2JZQDE2CHW7ZhLODEAAAD9U7apVCcoFt4qA6HkeCrCJpsYut2di61kZ4i3FQCd7aoU6vYVwAA=", dominant: "#080808", w: 2560, h: 1600 },
  "/themes/coast.webp": { lqip: "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAwAwCdASoUAAwALrV2u12jqampiYC0SyAE6ZQAHUQbj10AAP6UiWJZVs9s5Ik4Q85PWFwdqQ4XW/+2aQGXJ7rWTlxQkNqy6XcBfN5iTggAAA==", dominant: "#c8b8a8", w: 2560, h: 1600 },
  "/themes/dark-1.webp": { lqip: "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAABQAwCdASoUAAwAPu1iqU2ppaQiMAgBMB2JZwDImCHfh+eQwAD+9CLtOg9zgQpe2NA7oqojwAA=", dominant: "#080808", w: 2560, h: 1600 },
  "/themes/dark-2.webp": { lqip: "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAwCdASoUAAwAPu1iqU2ppaOiMAgBMB2JZwC+SCHdmmj8nDIgSAAA/vQjflpYt+ls6gaB25FXRlwv+qBCAAAA", dominant: "#080808", w: 2560, h: 1600 },
  "/themes/gradient-1.webp": { lqip: "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAACQBACdASoUAAwAPu1iqU2ppaOiMAgBMB2JbACdMoLUABGBfAnOFH4HDM/U1AAA/o9jzbsVXXvTulWlGShosHPvXVsYj3on9JBjE2iCO2dEVMTBviTqDfWlPHd2Ziwrjo3RChtL373KTFvV6+4e/zNUfyvmSmo4QQAAAA==", dominant: "#d8d8d8", w: 2560, h: 1600 },
  "/themes/linen-dark.webp": { lqip: "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAABwAwCdASoUABcAPu1wr1KtJiQjqAgBoB2JaQAAPPSr3b4OVAAA/vBByOi6ldjbKZTMY5mSLzFa+AAA", dominant: "#080808", w: 1408, h: 1600 },
  "/themes/market-warm.webp": { lqip: "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAABwBgCdASoUABwAPu1orFEppaQiqAqpMB2JbACdMtU0T9K8wAYL3X8lI2xX5yfoD648ugOIlgMzd0cIFAAA+KWYhQ3HZDTXuFeGbGi9Fcyn/+BOZSGPE5Pr+J2apmFL7NAQRxKijgJnTm7U0joQpCaWUwBWsGP8yAGG5Hp698vZcAUoURUnx1+2Ysj5eGRq+TIsBNVj7lthwX8EAAA=", dominant: "#f89808", w: 1152, h: 1600 },
  "/themes/mesh-lime.webp": { lqip: "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQBACdASoUAAwAPu1iqU2ppaQiMAgBMB2JQBdl4AAvdAKxv5sbW6dz6AD+7qFRmP6lyPCIuA9EUnvgmRdeNROvNykCizA8ZDKWkiz6X2AAAA==", dominant: "#182828", w: 2560, h: 1600 },
  "/themes/mesh-navy.webp": { lqip: "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAwCdASoUAAwAPu1kqk4ppaQiMAgBMB2JYwAAUXy7aTV/ztZ+4AAA/vDfraO+snDx48fcwpiGRH0HxbhiWEklOxG2N+YAAAA=", dominant: "#081828", w: 2560, h: 1600 },
  "/themes/mount-kenya.webp": { lqip: "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQBACdASoUAA8APu1iqk2ppaQiMAgBMB2JYwCdIIjDAWvVjcngxiZYAADyc8vFu6aECKXmOEqlc6Yj8/e2Lgv5Hou5MTmRXdUSJno0aVTOjtwbJ0LCUH9kXXXnwAAA", dominant: "#080808", w: 2176, h: 1600 },
  "/themes/nairobi-dawn.webp": { lqip: "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAwCdASoUAA8APu1kqU2ppaQiMAgBMB2JZQCo9CHHNrwMHA8GAAD92CCrw4OK69ixwyxRNr0oAN4Rg4Ny1dQJksyRYjMo7JeAAA==", dominant: "#989898", w: 2176, h: 1600 },
  "/themes/paper.webp": { lqip: "data:image/webp;base64,UklGRjIAAABXRUJQVlA4ICYAAACwAgCdASoUAAwAPu1iqU2ppaOiMAgBMB2JaQAAeyAA/vB6K2cgAA==", dominant: "#f8f8f8", w: 2560, h: 1600 },
  "/themes/savannah.webp": { lqip: "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAABQAwCdASoUAAwAPu1iqU2ppaQiMAgBMB2JagCdMoAEZxAMIgD+6YA/ePMug76ktUlAt/tT5NOD6a9bu+h9Xg8s70fKph1AAAA=", dominant: "#b83828", w: 2560, h: 1600 },
  "/themes/sunset-silhouette.webp": { lqip: "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAwCdASoUAAwAPu1iqU2ppaQiMAgBMB2JaACdACHe0FVvu270/xq4AP7o1qJdNfZmOw3B3l9i222uMXcT8Xds2w4J+GJHJt8diKm0AAA=", dominant: "#080808", w: 2560, h: 1600 },
  "/themes/tea-fields.webp": { lqip: "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAAAwBQCdASoUABwAPu1krE+ppSQiMBgIATAdiUAUu3gQHIsNlahq5jo+9jXkR9vzN6UZAAD9JdqhQc1LcbjGU9bsuUcTWCE0ButWAIXmlOcZjwdYewDMzMtSutcaR+Nfsb1Nns6vroDjqphrFgVnx5aRCQOm28C7imQmETcAAAA=", dominant: "#081808", w: 1152, h: 1600 },
};

/** Never throws on an unknown path: a missing entry means "no placeholder", and
 *  every consumer already survives that - a skin whose file has not been
 *  delivered renders its ground and its accent wash, which is a finished-looking
 *  floor rather than a broken one. */
export const metaFor = (src: string | null | undefined): MediaMeta | null =>
  (src ? MEDIA[src] ?? null : null);
