// ─────────────────────────────────────────────────────────────────────────────
// RIRI ANALYTICS — EXPORTS.
//
// A real .xlsx and a real .pdf, generated server-side from the SAME rows the answer was
// read from, written to private storage under an autogenerated name, handed back as a
// signed link.
//
// NOT a screen print. ServiceSuite's own reports already work this way (ClosedXML →
// MemoryStream → File(bytes, mime, "INCOME_STATEMENT_{start}_{end}.xlsx")), and the
// people we are selling to expect a workbook they can pivot, not a picture of a table.
// A screenshot of numbers is not data; it is a rumour about data.
//
// THE ROWS ARE RE-READ, NEVER POSTED. The client sends the query id; the server re-runs
// the same guarded SQL and exports what comes back. If the browser posted the rows, a
// customer could edit a figure in devtools and download an official-looking BirgenAI
// workbook containing it.
// ─────────────────────────────────────────────────────────────────────────────
import ExcelJS from "exceljs";
import PDFDocument from "pdfkit";

export type ExportRow = Record<string, unknown>;

export type ExportMeta = {
  /** The question, verbatim — it becomes the title and the filename. */
  question: string;
  lenderName: string;
  /** The SQL that produced these rows. Printed on the export: the number is checkable. */
  sql?: string | null;
  /** Who asked, for the footer. */
  actorName?: string | null;
};

/**
 * The autogenerated name, ServiceSuite-style: SCREAMING_SNAKE of the question + the day.
 *
 *   "What's my PAR 30 by product?" → RIRI_WHATS_MY_PAR_30_BY_PRODUCT_2026-07-16.xlsx
 *
 * Derived from the question rather than a uuid because the file leaves our system the
 * moment it is downloaded — into an inbox, a WhatsApp group, a board pack — and it has
 * to say what it is from the filename alone.
 */
export function exportName(question: string, ext: "xlsx" | "pdf", when = new Date()): string {
  const slug = question
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 60)
    .replace(/_+$/, "");
  const day = when.toISOString().slice(0, 10);
  return `RIRI_${slug || "REPORT"}_${day}.${ext}`;
}

const isNum = (v: unknown): v is number => typeof v === "number" && Number.isFinite(v);

/** Cells as text — Dates and Decimals must not reach a sheet as "[object Object]". */
function cell(v: unknown): string | number | Date {
  if (v === null || v === undefined) return "";
  if (isNum(v)) return v;
  if (v instanceof Date) return v;
  if (typeof v === "object" && v !== null && "toNumber" in v && typeof (v as { toNumber: unknown }).toNumber === "function") {
    return (v as { toNumber: () => number }).toNumber(); // Prisma.Decimal
  }
  return String(v);
}

export async function toExcel(rows: ExportRow[], meta: ExportMeta): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "BirgenAI · Riri Analytics";
  wb.created = new Date();

  const ws = wb.addWorksheet("Report", { views: [{ state: "frozen", ySplit: 4 }] });
  const cols = rows.length ? Object.keys(rows[0]) : [];

  // A header block, so the sheet still explains itself once it is three forwards deep
  // in somebody's inbox.
  ws.mergeCells(1, 1, 1, Math.max(1, cols.length));
  ws.getCell(1, 1).value = meta.question;
  ws.getCell(1, 1).font = { bold: true, size: 14 };
  ws.mergeCells(2, 1, 2, Math.max(1, cols.length));
  ws.getCell(2, 1).value = `${meta.lenderName} · generated ${new Date().toISOString().slice(0, 16).replace("T", " ")}${meta.actorName ? ` · by ${meta.actorName}` : ""}`;
  ws.getCell(2, 1).font = { size: 9, color: { argb: "FF888888" } };

  if (cols.length === 0) {
    ws.getCell(4, 1).value = "No rows.";
    return Buffer.from(await wb.xlsx.writeBuffer());
  }

  const head = ws.getRow(4);
  head.values = cols;
  head.font = { bold: true };
  head.eachCell((c) => {
    c.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF1F1F4" } };
    c.border = { bottom: { style: "thin", color: { argb: "FFCCCCCC" } } };
  });

  for (const r of rows) ws.addRow(cols.map((c) => cell(r[c])));

  // Width from the content, so nothing lands as ####.
  ws.columns.forEach((col, i) => {
    const longest = Math.max(
      cols[i].length,
      ...rows.slice(0, 200).map((r) => String(r[cols[i]] ?? "").length),
    );
    col.width = Math.min(48, Math.max(10, longest + 2));
  });
  ws.autoFilter = { from: { row: 4, column: 1 }, to: { row: 4, column: cols.length } };

  // The SQL rides along on its own sheet — the same "you can check this" promise the
  // chat panel makes, kept once the file has left the chat panel.
  if (meta.sql) {
    const s = wb.addWorksheet("Query");
    s.getCell(1, 1).value = "The query that produced this report";
    s.getCell(1, 1).font = { bold: true };
    s.getCell(3, 1).value = meta.sql;
    s.getCell(3, 1).alignment = { wrapText: true, vertical: "top" };
    s.getColumn(1).width = 120;
  }

  return Buffer.from(await wb.xlsx.writeBuffer());
}

export async function toPdf(rows: ExportRow[], meta: ExportMeta): Promise<Buffer> {
  const cols = rows.length ? Object.keys(rows[0]) : [];
  // Landscape once a table is wide — a 7-column report on portrait A4 is unreadable.
  const doc = new PDFDocument({ size: "A4", layout: cols.length > 4 ? "landscape" : "portrait", margin: 36 });

  const chunks: Buffer[] = [];
  doc.on("data", (c: Buffer) => chunks.push(c));
  const done = new Promise<Buffer>((resolve) => doc.on("end", () => resolve(Buffer.concat(chunks))));

  doc.fontSize(15).fillColor("#111").text(meta.question, { width: doc.page.width - 72 });
  doc.moveDown(0.2);
  doc.fontSize(8).fillColor("#888").text(
    `${meta.lenderName} · generated ${new Date().toISOString().slice(0, 16).replace("T", " ")}${meta.actorName ? ` · by ${meta.actorName}` : ""}`,
  );
  doc.moveDown(0.8);

  if (cols.length === 0) {
    doc.fontSize(10).fillColor("#333").text("No rows.");
    doc.end();
    return done;
  }

  const avail = doc.page.width - 72;
  const w = avail / cols.length;
  const line = (y: number) => doc.moveTo(36, y).lineTo(doc.page.width - 36, y).strokeColor("#ddd").lineWidth(0.5).stroke();

  const header = (y: number) => {
    doc.fontSize(8).fillColor("#555");
    cols.forEach((c, i) => doc.text(String(c), 36 + i * w, y, { width: w - 4, ellipsis: true }));
    line(y + 11);
    return y + 15;
  };

  let y = header(doc.y);
  for (const r of rows) {
    // A new page needs its header repeated, or page 2 is a wall of unlabelled numbers.
    if (y > doc.page.height - 54) { doc.addPage(); y = header(36); }
    doc.fontSize(8).fillColor("#222");
    cols.forEach((c, i) => {
      const v = r[c];
      doc.text(v === null || v === undefined ? "" : String(cell(v)), 36 + i * w, y, {
        width: w - 4, ellipsis: true, align: isNum(v) ? "right" : "left",
      });
    });
    y += 13;
  }

  line(y + 2);
  doc.fontSize(7).fillColor("#999").text(`${rows.length} row(s)`, 36, y + 6);
  if (meta.sql) {
    doc.addPage({ size: "A4", layout: "portrait", margin: 36 });
    doc.fontSize(10).fillColor("#111").text("The query that produced this report");
    doc.moveDown(0.5);
    doc.fontSize(7).fillColor("#555").font("Courier").text(meta.sql, { width: doc.page.width - 72 });
  }

  doc.end();
  return done;
}

export const EXPORT_MIME = {
  xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  pdf: "application/pdf",
} as const;
