// ─────────────────────────────────────────────────────────────────────────────
// RIRI ANALYTICS — EXPORTS.
//
// A real .xlsx and a real .pdf, generated server-side from the SAME rows the answer was
// read from, written to private storage under an autogenerated name, handed back as a
// signed link.
//
// NOT a screen print. ServiceSuite's own reports already work this way (ClosedXML →
// MemoryStream → File(bytes, mime, "INCOME_STATEMENT_{start}_{end}.xlsx")), and the
// people we are selling to expect a workbook they can pivot, not a picture of a table.
// A screenshot of numbers is not data; it is a rumour about data.
//
// THE ROWS ARE RE-READ, NEVER POSTED. The client sends the query id; the server re-runs
// the same guarded SQL and exports what comes back. If the browser posted the rows, a
// customer could edit a figure in devtools and download an official-looking BirgenAI
// workbook containing it.
// ─────────────────────────────────────────────────────────────────────────────
import ExcelJS from "exceljs";
import PDFDocument from "pdfkit";
import { planChart, fmtValue, humanise, rampColor, gridlines, niceMax, type ChartPlan } from "./charts";

export type ExportRow = Record<string, unknown>;

export type ExportMeta = {
  /** The question, verbatim — it becomes the title and the filename. */
  question: string;
  lenderName: string;
  /** The SQL that produced these rows. Printed on the export: the number is checkable. */
  sql?: string | null;
  /** Who asked, for the footer. */
  actorName?: string | null;
  /** The lender's brand hex — the report wears their colour like every other artifact. */
  accent?: string | null;
  accent2?: string | null;
};

/**
 * The autogenerated name, ServiceSuite-style: SCREAMING_SNAKE of the question + the day.
 *
 *   "What's my PAR 30 by product?" → RIRI_WHATS_MY_PAR_30_BY_PRODUCT_2026-07-16.xlsx
 *
 * Derived from the question rather than a uuid because the file leaves our system the
 * moment it is downloaded — into an inbox, a WhatsApp group, a board pack — and it has
 * to say what it is from the filename alone.
 */
export function exportName(question: string, ext: "xlsx" | "pdf", when = new Date()): string {
  const slug = question
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 60)
    .replace(/_+$/, "");
  const day = when.toISOString().slice(0, 10);
  return `RIRI_${slug || "REPORT"}_${day}.${ext}`;
}

const isNum = (v: unknown): v is number => typeof v === "number" && Number.isFinite(v);

/** Cells as text — Dates and Decimals must not reach a sheet as "[object Object]". */
function cell(v: unknown): string | number | Date {
  if (v === null || v === undefined) return "";
  if (isNum(v)) return v;
  if (v instanceof Date) return v;
  if (typeof v === "object" && v !== null && "toNumber" in v && typeof (v as { toNumber: unknown }).toNumber === "function") {
    return (v as { toNumber: () => number }).toNumber(); // Prisma.Decimal
  }
  return String(v);
}

export async function toExcel(rows: ExportRow[], meta: ExportMeta): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "BirgenAI · ServiceSuite AI";
  wb.created = new Date();

  const ws = wb.addWorksheet("Report", { views: [{ state: "frozen", ySplit: 4 }] });
  const cols = rows.length ? Object.keys(rows[0]) : [];

  // A header block, so the sheet still explains itself once it is three forwards deep
  // in somebody's inbox.
  ws.mergeCells(1, 1, 1, Math.max(1, cols.length));
  ws.getCell(1, 1).value = meta.question;
  ws.getCell(1, 1).font = { bold: true, size: 14 };
  ws.mergeCells(2, 1, 2, Math.max(1, cols.length));
  ws.getCell(2, 1).value = `${meta.lenderName} · generated ${new Date().toISOString().slice(0, 16).replace("T", " ")}${meta.actorName ? ` · by ${meta.actorName}` : ""}`;
  ws.getCell(2, 1).font = { size: 9, color: { argb: "FF888888" } };

  if (cols.length === 0) {
    ws.getCell(4, 1).value = "No rows.";
    return Buffer.from(await wb.xlsx.writeBuffer());
  }

  const head = ws.getRow(4);
  head.values = cols;
  head.font = { bold: true };
  head.eachCell((c) => {
    c.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF1F1F4" } };
    c.border = { bottom: { style: "thin", color: { argb: "FFCCCCCC" } } };
  });

  for (const r of rows) ws.addRow(cols.map((c) => cell(r[c])));

  // Width from the content, so nothing lands as ####.
  ws.columns.forEach((col, i) => {
    const longest = Math.max(
      cols[i].length,
      ...rows.slice(0, 200).map((r) => String(r[cols[i]] ?? "").length),
    );
    col.width = Math.min(48, Math.max(10, longest + 2));
  });
  ws.autoFilter = { from: { row: 4, column: 1 }, to: { row: 4, column: cols.length } };

  // The SQL rides along on its own sheet — the same "you can check this" promise the
  // chat panel makes, kept once the file has left the chat panel.
  if (meta.sql) {
    const s = wb.addWorksheet("Query");
    s.getCell(1, 1).value = "The query that produced this report";
    s.getCell(1, 1).font = { bold: true };
    s.getCell(3, 1).value = meta.sql;
    s.getCell(3, 1).alignment = { wrapText: true, vertical: "top" };
    s.getColumn(1).width = 120;
  }

  return Buffer.from(await wb.xlsx.writeBuffer());
}

// ── The report ───────────────────────────────────────────────────────────────
//
// Built to be FORWARDED. These files leave our system the moment they are
// downloaded — into an inbox, a WhatsApp group, a board pack — and once there they
// are the only thing representing us. So the layout is the one a finance audience
// already reads: a branded band, a KPI row, ONE chart that was chosen rather than
// defaulted to, then the table, then the query that produced it.
//
// Everything is drawn with pdfkit vector primitives — no headless browser, no
// chart-image service, no network call. A report generator that depends on
// rendering a web page somewhere else is a report generator that falls over at
// month end, when every lender runs one at once.
//
// The chart TYPE is inferred (see charts.ts) and the reason is printed on the
// page, so a reader who disagrees can see why that shape was chosen instead of
// assuming the tool only knows one.

const INK = "#18181b";
const MUTED = "#71717a";
const FAINT = "#a1a1aa";
const HAIRLINE = "#e4e4e7";

/** The one place a colour from outside is trusted — and only if it is a hex. */
function safeHex(v: string | null | undefined, fallback: string): string {
  return /^#[0-9a-fA-F]{6}$/.test(v ?? "") ? (v as string) : fallback;
}

type Ctx = InstanceType<typeof PDFDocument>;

/** The brand band across the top of page 1 — the thing that says whose report this is. */
function coverBand(doc: Ctx, meta: ExportMeta, plan: ChartPlan, accent: string, accent2: string) {
  const W = doc.page.width;
  doc.save();
  doc.rect(0, 0, W, 96).fill(accent);
  // A second, lighter wedge, so the band reads as designed rather than as a
  // rectangle somebody filled in.
  doc.rect(W * 0.63, 0, W * 0.37, 96).fill(accent2);
  doc.restore();

  doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(8)
    .text(meta.lenderName.toUpperCase(), 40, 24, { characterSpacing: 1.4, width: W - 80, ellipsis: true });
  doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(17)
    .text(plan.title, 40, 40, { width: W - 80, height: 34, ellipsis: true });
  doc.fillColor("#ffffff").font("Helvetica").fontSize(7.5).fillOpacity(0.85)
    .text(
      `Generated ${new Date().toISOString().slice(0, 16).replace("T", " ")}${meta.actorName ? ` by ${meta.actorName}` : ""}  ·  ServiceSuite AI Analytics  ·  read-only, org-scoped`,
      40, 78, { width: W - 80, ellipsis: true },
    );
  doc.fillOpacity(1);
}

/** The KPI strip — the four numbers someone reads before deciding to read the rest. */
function kpiRow(doc: Ctx, plan: ChartPlan, y: number, accent: string): number {
  if (plan.kpis.length === 0) return y;
  const W = doc.page.width;
  const gap = 10;
  const n = Math.min(4, plan.kpis.length);
  const w = (W - 80 - gap * (n - 1)) / n;

  plan.kpis.slice(0, n).forEach((k, i) => {
    const x = 40 + i * (w + gap);
    doc.roundedRect(x, y, w, 52, 6).fillAndStroke("#fafafa", HAIRLINE);
    doc.fillColor(MUTED).font("Helvetica-Bold").fontSize(6.5)
      .text(k.label.toUpperCase(), x + 10, y + 11, { width: w - 20, characterSpacing: 0.8, ellipsis: true });
    doc.fillColor(accent).font("Helvetica-Bold").fontSize(15)
      .text(k.value, x + 10, y + 24, { width: w - 20, ellipsis: true });
  });
  return y + 52 + 20;
}

/** Horizontal bars — magnitude across categories, largest first, every bar labelled. */
function barChart(doc: Ctx, plan: ChartPlan, y: number, height: number): number {
  const W = doc.page.width;
  const left = 40;
  const right = W - 40;
  const labelW = Math.min(150, (right - left) * 0.3);
  const plotL = left + labelW + 8;
  const valueW = 64;
  const plotR = right - valueW;
  const max = Math.max(...plan.points.map((p) => p.value), 0);
  const top = niceMax(max);
  const rowH = Math.min(26, Math.max(14, height / Math.max(1, plan.points.length)));
  const bottom = y + plan.points.length * rowH;

  // Gridlines behind the bars, recessive — scaffolding, not data.
  gridlines(max, 4).forEach((g) => {
    const x = plotL + (top > 0 ? g / top : 0) * (plotR - plotL);
    doc.moveTo(x, y).lineTo(x, bottom).strokeColor(HAIRLINE).lineWidth(0.5).stroke();
    doc.fillColor(FAINT).font("Helvetica").fontSize(6)
      .text(fmtValue(g, plan.unit), x - 20, bottom + 4, { width: 40, align: "center" });
  });

  plan.points.forEach((p, i) => {
    const by = y + i * rowH;
    const bh = rowH - 6;
    const bw = top > 0 ? Math.max(1.5, (p.value / top) * (plotR - plotL)) : 1.5;
    const t = max > 0 ? p.value / max : 0;

    doc.fillColor(INK).font("Helvetica").fontSize(7.5)
      .text(p.label, left, by + bh / 2 - 4, { width: labelW, align: "right", ellipsis: true });
    // Rounded data-end anchored to the baseline.
    doc.roundedRect(plotL, by, bw, bh, Math.min(3, bh / 2)).fill(rampColor(t));
    // The direct label is not decoration. The ramp's lighter steps sit under 3:1
    // against white, so the number has to be readable without relying on colour.
    doc.fillColor(INK).font("Helvetica-Bold").fontSize(7.5)
      .text(fmtValue(p.value, plan.unit), plotR + 6, by + bh / 2 - 4, { width: valueW - 6, ellipsis: true });
  });

  return bottom + 20;
}

/** Columns — a period axis, in time order. Never re-sorted by size. */
function columnChart(doc: Ctx, plan: ChartPlan, y: number, height: number): number {
  const W = doc.page.width;
  const left = 40;
  const right = W - 40;
  const axisW = 46;
  const plotL = left + axisW;
  const plotB = y + height;
  const max = Math.max(...plan.points.map((p) => p.value), 0);
  const top = niceMax(max);
  const n = plan.points.length;
  const slot = (right - plotL) / Math.max(1, n);
  const bw = Math.min(46, slot * 0.62);

  gridlines(max, 4).forEach((g) => {
    const gy = plotB - (top > 0 ? g / top : 0) * height;
    doc.moveTo(plotL, gy).lineTo(right, gy).strokeColor(HAIRLINE).lineWidth(0.5).stroke();
    doc.fillColor(FAINT).font("Helvetica").fontSize(6)
      .text(fmtValue(g, plan.unit), left, gy - 3, { width: axisW - 6, align: "right" });
  });

  plan.points.forEach((p, i) => {
    const x = plotL + i * slot + (slot - bw) / 2;
    const bh = top > 0 ? Math.max(1.5, (p.value / top) * height) : 1.5;
    const t = max > 0 ? p.value / max : 0;
    doc.roundedRect(x, plotB - bh, bw, bh, Math.min(3, bw / 2)).fill(rampColor(t));
    doc.fillColor(INK).font("Helvetica-Bold").fontSize(6)
      .text(fmtValue(p.value, plan.unit), x - 8, plotB - bh - 9, { width: bw + 16, align: "center" });
    doc.fillColor(MUTED).font("Helvetica").fontSize(6)
      .text(p.label.slice(-7), x - 8, plotB + 5, { width: bw + 16, align: "center", ellipsis: true });
  });

  doc.moveTo(plotL, plotB).lineTo(right, plotB).strokeColor("#d4d4d8").lineWidth(0.7).stroke();
  return plotB + 22;
}

/** One number, large. A single value is a figure, not a one-bar chart. */
function heroFigure(doc: Ctx, plan: ChartPlan, y: number, accent: string): number {
  const W = doc.page.width;
  const p = plan.points[0];
  doc.roundedRect(40, y, W - 80, 92, 8).fillAndStroke("#fafafa", HAIRLINE);
  doc.fillColor(MUTED).font("Helvetica-Bold").fontSize(7)
    .text(humanise(plan.valueKey ?? "").toUpperCase(), 56, y + 18, { characterSpacing: 1, width: W - 112, ellipsis: true });
  doc.fillColor(accent).font("Helvetica-Bold").fontSize(38)
    .text(fmtValue(p.value, plan.unit), 56, y + 34, { width: W - 112, ellipsis: true });
  return y + 92 + 20;
}

/** The rows, always — a chart is a READING of the data, never a replacement for it. */
function dataTable(doc: Ctx, rows: ExportRow[], y: number): number {
  const cols = rows.length ? Object.keys(rows[0]) : [];
  if (!cols.length) return y;
  const avail = doc.page.width - 80;
  const w = avail / cols.length;

  const head = (yy: number) => {
    doc.rect(40, yy - 3, avail, 16).fill("#f4f4f5");
    doc.fillColor(MUTED).font("Helvetica-Bold").fontSize(6.5);
    cols.forEach((c, i) => doc.text(humanise(c).toUpperCase(), 44 + i * w, yy + 1, { width: w - 8, ellipsis: true }));
    return yy + 18;
  };

  doc.fillColor(INK).font("Helvetica-Bold").fontSize(9).text("The data", 40, y);
  let yy = head(y + 16);

  rows.forEach((r, ri) => {
    // A new page needs its header repeated, or page 2 is a wall of unlabelled numbers.
    if (yy > doc.page.height - 56) { doc.addPage(); yy = head(48); }
    if (ri % 2 === 1) doc.rect(40, yy - 3, avail, 13).fill("#fbfbfb");
    doc.fillColor("#3f3f46").font("Helvetica").fontSize(7);
    cols.forEach((c, i) => {
      const v = r[c];
      doc.text(v === null || v === undefined ? "" : String(cell(v)), 44 + i * w, yy, {
        width: w - 8, ellipsis: true, align: isNum(v) ? "right" : "left",
      });
    });
    yy += 13;
  });
  return yy;
}

export async function toPdf(rows: ExportRow[], meta: ExportMeta): Promise<Buffer> {
  const plan = planChart(rows, meta.question);
  const accent = safeHex(meta.accent, "#18181b");
  const accent2 = safeHex(meta.accent2, accent);

  // Orientation follows the widest thing on the page, which is always the table —
  // the chart is laid out to whatever page it is given.
  const colCount = rows.length ? Object.keys(rows[0]).length : 0;
  const doc = new PDFDocument({ size: "A4", layout: colCount > 5 ? "landscape" : "portrait", margin: 40 });

  const chunks: Buffer[] = [];
  doc.on("data", (c: Buffer) => chunks.push(c));
  const done = new Promise<Buffer>((resolve) => doc.on("end", () => resolve(Buffer.concat(chunks))));

  coverBand(doc, meta, plan, accent, accent2);

  let y = 118;
  y = kpiRow(doc, plan, y, accent);

  if (plan.form !== "table" && plan.points.length > 0) {
    doc.fillColor(FAINT).font("Helvetica-Oblique").fontSize(6.5)
      .text(plan.rationale, 40, y - 14, { width: doc.page.width - 80, ellipsis: true });

    const room = Math.min(240, doc.page.height - y - 200);
    y = plan.form === "hero"
      ? heroFigure(doc, plan, y, accent)
      : plan.form === "bar"
        ? barChart(doc, plan, y, Math.max(70, room))
        : columnChart(doc, plan, y, Math.max(90, room));
  }

  if (rows.length === 0) {
    doc.fillColor(MUTED).font("Helvetica").fontSize(10).text("No rows matched this question.", 40, y);
  } else {
    y = dataTable(doc, rows, y + 4);
    doc.fillColor(FAINT).font("Helvetica").fontSize(6.5)
      .text(`${rows.length} row${rows.length === 1 ? "" : "s"}`, 40, y + 6);
  }

  // The query, on its own page. The promise the chat panel makes — "you can check
  // this number" — has to survive the file leaving the chat panel.
  if (meta.sql) {
    doc.addPage({ size: "A4", layout: "portrait", margin: 40 });
    doc.rect(0, 0, doc.page.width, 6).fill(accent);
    doc.fillColor(INK).font("Helvetica-Bold").fontSize(11)
      .text("The query that produced this report", 40, 42);
    doc.fillColor(MUTED).font("Helvetica").fontSize(7.5)
      .text("Read-only, and scoped to your organisation by the database itself. Re-run it and you will get these rows.",
        40, 60, { width: doc.page.width - 80 });
    doc.fillColor("#3f3f46").font("Courier").fontSize(7.5)
      .text(meta.sql, 40, 86, { width: doc.page.width - 80 });
  }

  doc.end();
  return done;
}

export const EXPORT_MIME = {
  xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  pdf: "application/pdf",
} as const;
